//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VHaaSh.API.Modals.Database_Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class T8GymDBEntities : DbContext
    {
        public T8GymDBEntities()
            : base("name=T8GymDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<TblAppointment> TblAppointments { get; set; }
        public virtual DbSet<TblBatch> TblBatches { get; set; }
        public virtual DbSet<TblBloodDetail> TblBloodDetails { get; set; }
        public virtual DbSet<TblCity> TblCities { get; set; }
        public virtual DbSet<TblCorporateMembership> TblCorporateMemberships { get; set; }
        public virtual DbSet<TblCustomizedPlan> TblCustomizedPlans { get; set; }
        public virtual DbSet<TblEventDetail> TblEventDetails { get; set; }
        public virtual DbSet<TblGallery> TblGalleries { get; set; }
        public virtual DbSet<TblGender> TblGenders { get; set; }
        public virtual DbSet<TblHolidayDetail> TblHolidayDetails { get; set; }
        public virtual DbSet<TblLevel> TblLevels { get; set; }
        public virtual DbSet<TblLog> TblLogs { get; set; }
        public virtual DbSet<TblMaintenance> TblMaintenances { get; set; }
        public virtual DbSet<TblMember> TblMembers { get; set; }
        public virtual DbSet<TblMembership> TblMemberships { get; set; }
        public virtual DbSet<TblNutritionist> TblNutritionists { get; set; }
        public virtual DbSet<TblOfferDetail> TblOfferDetails { get; set; }
        public virtual DbSet<TblOwner> TblOwners { get; set; }
        public virtual DbSet<TblPaymentDetail> TblPaymentDetails { get; set; }
        public virtual DbSet<TblPaymentMode> TblPaymentModes { get; set; }
        public virtual DbSet<TblRole> TblRoles { get; set; }
        public virtual DbSet<TblStaff> TblStaffs { get; set; }
        public virtual DbSet<TblState> TblStates { get; set; }
        public virtual DbSet<TblSupplement> TblSupplements { get; set; }
        public virtual DbSet<TblTrainer> TblTrainers { get; set; }
        public virtual DbSet<TblUserRole> TblUserRoles { get; set; }
        public virtual DbSet<TblUser> TblUsers { get; set; }
        public virtual DbSet<TblUserType> TblUserTypes { get; set; }
    }
}
