//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VHaaSh.API.Modals.Database_Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblBatch
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TblBatch()
        {
            this.TblMembers = new HashSet<TblMember>();
        }
    
        public int ID { get; set; }
        public string Activity { get; set; }
        public double Duration__hr_ { get; set; }
        public string WeekDay { get; set; }
        public Nullable<int> TrainierId { get; set; }
    
        public virtual TblStaff TblStaff { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TblMember> TblMembers { get; set; }
    }
}
