//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VHaaSh.API.Modals.Database_Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblCorporateMembership
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TblCorporateMembership()
        {
            this.TblMembers = new HashSet<TblMember>();
        }
    
        public int ID { get; set; }
        public string CompanyName { get; set; }
        public int MemberCount { get; set; }
        public int Duration__mm_ { get; set; }
        public int Discount { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TblMember> TblMembers { get; set; }
    }
}
