//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VHaaSh.API.Modals.Database_Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblCustomizedPlan
    {
        public int ID { get; set; }
        public int MemberId { get; set; }
        public double NutritionPlanCharge { get; set; }
        public byte[] CustomizedNutritionPlan { get; set; }
        public double TrainingPlanCharge { get; set; }
        public byte[] CustomizedTrainingPlan { get; set; }
        public Nullable<int> NutritionistID { get; set; }
        public Nullable<int> TrainerID { get; set; }
        public Nullable<int> SupplimentId { get; set; }
    
        public virtual TblMember TblMember { get; set; }
        public virtual TblStaff TblStaff { get; set; }
        public virtual TblSupplement TblSupplement { get; set; }
        public virtual TblStaff TblStaff1 { get; set; }
    }
}
