//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VHaaSh.API.Modals.Database_Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblMembership
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TblMembership()
        {
            this.TblMembers = new HashSet<TblMember>();
            this.TblPaymentDetails = new HashSet<TblPaymentDetail>();
        }
    
        public int ID { get; set; }
        public string Name { get; set; }
        public int Fee { get; set; }
        public Nullable<bool> Swimming { get; set; }
        public Nullable<bool> Cardio { get; set; }
        public Nullable<bool> StrengthTraining { get; set; }
        public Nullable<bool> SteamBath { get; set; }
        public Nullable<bool> CrossFit { get; set; }
        public Nullable<bool> Boxing { get; set; }
        public Nullable<bool> Zumba { get; set; }
        public Nullable<bool> BasicWorkoutPlan { get; set; }
        public Nullable<bool> CustomWorkoutPlan { get; set; }
        public Nullable<bool> BasicDietPlan { get; set; }
        public Nullable<bool> CustomDietPlan { get; set; }
        public Nullable<int> RecommendedLevel { get; set; }
    
        public virtual TblLevel TblLevel { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TblMember> TblMembers { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TblPaymentDetail> TblPaymentDetails { get; set; }
    }
}
