//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VHaaSh.API.Modals.Database_Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblMember
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TblMember()
        {
            this.TblCustomizedPlans = new HashSet<TblCustomizedPlan>();
            this.TblPaymentDetails = new HashSet<TblPaymentDetail>();
        }
    
        public int ID { get; set; }
        public string Name { get; set; }
        public int Age { get; set; }
        public Nullable<int> GenderID { get; set; }
        public Nullable<int> BloodId { get; set; }
        public Nullable<double> Weight { get; set; }
        public Nullable<double> Height { get; set; }
        public Nullable<double> BMI { get; set; }
        public string Contact { get; set; }
        public string Email { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<System.DateTime> AdmissionDate { get; set; }
        public byte[] DietPlan { get; set; }
        public string InjuryDetails { get; set; }
        public byte[] ProfilePhoto { get; set; }
        public Nullable<int> TrainningLevelID { get; set; }
        public Nullable<int> TrainerID { get; set; }
        public Nullable<int> NutritionistID { get; set; }
        public Nullable<int> BatchID { get; set; }
        public Nullable<int> MembershipID { get; set; }
        public Nullable<int> CorporateMembershipID { get; set; }
        public Nullable<int> StateID { get; set; }
        public Nullable<int> CityID { get; set; }
        public Nullable<int> UserID { get; set; }
    
        public virtual TblBatch TblBatch { get; set; }
        public virtual TblBloodDetail TblBloodDetail { get; set; }
        public virtual TblCity TblCity { get; set; }
        public virtual TblCorporateMembership TblCorporateMembership { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TblCustomizedPlan> TblCustomizedPlans { get; set; }
        public virtual TblGender TblGender { get; set; }
        public virtual TblLevel TblLevel { get; set; }
        public virtual TblMembership TblMembership { get; set; }
        public virtual TblStaff TblStaff { get; set; }
        public virtual TblState TblState { get; set; }
        public virtual TblStaff TblStaff1 { get; set; }
        public virtual TblUser TblUser { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TblPaymentDetail> TblPaymentDetails { get; set; }
    }
}
