//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VHaaSh.API.Modals.Database_Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblPaymentDetail
    {
        public int ID { get; set; }
        public string ReceiverName { get; set; }
        public int PaidAmount { get; set; }
        public int MemberID { get; set; }
        public int MembershipID { get; set; }
        public int PaymentModeID { get; set; }
    
        public virtual TblMember TblMember { get; set; }
        public virtual TblMembership TblMembership { get; set; }
        public virtual TblPaymentMode TblPaymentMode { get; set; }
    }
}
