//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VHaaSh.API.Modals.Database_Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblStaff
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TblStaff()
        {
            this.TblBatches = new HashSet<TblBatch>();
            this.TblCustomizedPlans = new HashSet<TblCustomizedPlan>();
            this.TblCustomizedPlans1 = new HashSet<TblCustomizedPlan>();
            this.TblMembers = new HashSet<TblMember>();
            this.TblMembers1 = new HashSet<TblMember>();
        }
    
        public int ID { get; set; }
        public string Name { get; set; }
        public string Contact { get; set; }
        public Nullable<double> Experience { get; set; }
        public string Certification { get; set; }
        public Nullable<double> Rating { get; set; }
        public int Age { get; set; }
        public string Achievements { get; set; }
        public Nullable<int> GenderID { get; set; }
        public Nullable<int> BloodId { get; set; }
        public Nullable<int> StateID { get; set; }
        public Nullable<int> CityId { get; set; }
        public Nullable<int> UserID { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TblBatch> TblBatches { get; set; }
        public virtual TblBloodDetail TblBloodDetail { get; set; }
        public virtual TblCity TblCity { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TblCustomizedPlan> TblCustomizedPlans { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TblCustomizedPlan> TblCustomizedPlans1 { get; set; }
        public virtual TblGender TblGender { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TblMember> TblMembers { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TblMember> TblMembers1 { get; set; }
        public virtual TblState TblState { get; set; }
        public virtual TblUser TblUser { get; set; }
    }
}
