//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VHaaSh.API.Modals.Database_Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblUserRole
    {
        public int RoleId { get; set; }
        public Nullable<int> UserId { get; set; }
        public Nullable<int> UserTypeId { get; set; }
    
        public virtual TblUser TblUser { get; set; }
        public virtual TblUserType TblUserType { get; set; }
    }
}
